trigger: none

pool:
  name: Linux-agent
  
stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - task: DotNetCoreCLI@2
            displayName: "Dotnet build"
            inputs:
              command: 'build'
              projects: '$(System.DefaultWorkingDirectory)/Applicaton.Web.API/Applicaton.Web.API.csproj'
              arguments: '--configuration Release'