trigger: none

pool:
  name: Linux-agent

variables:
- name: DOTNET_VERSION
  value: 6.x
- name: SOLUTION_FILE_LOCATION
  value: $(System.DefaultWorkingDirectory)/MotorMate.sln
- name: ARTIFACT_NAME
  value: "motormate-dotnet"
- name: OUTPUT_SOLUTION
  value: "$(System.DefaultWorkingDirectory)/output/$(ARTIFACT_NAME)"

stages:
  - stage: 
    displayName: "Dotnet Build & Publish"
    jobs:
      - job: 
        displayName: "Dotnet Build & Publish"
        steps:
          - task: CmdLine@2
            displayName: "Dotnet build"
            inputs:
              script: 'dotnet build $(SOLUTION_FILE_LOCATION) --configuration Release'
          - task: CmdLine@2
            displayName: "Dotnet publish"
            inputs:
              script: 'dotnet publish $(SOLUTION_FILE_LOCATION) -c Release -o $(OUTPUT_SOLUTION)'
          - task: CmdLine@2
            displayName: "List"
            inputs:
              script: 'ls -a'