name: Build and deploy ASP.Net
run-name: Build and deploy on "${{ github.ref_name }}" by "${{ github.actor }}"

on:
  push:
    branches: ["main", "develop", "feature/init-github-workflow"]
  pull_request:
    branches: ["main", "develop"]

env:
  SOLUTION_FILE_LOCATION: ${{ github.workspace }}/MotoMate.sln
  ARTIFACT_NAME: "dotnet-app"
  PROJECT_NAME: motomate
  RELEASE_PATH: ${{ env.DOTNET_ROOT }}/$ARTIFACT_NAME

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"
          dotnet-quality: "validated"

      - name: Build with dotnet
        run: dotnet build ${{ env.SOLUTION_FILE_LOCATION }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.SOLUTION_FILE_LOCATION }} -c Release -o ${{ env.RELEASE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: ${{ env.RELEASE_PATH }}

  deploy:
    name: Publish to Azure WebApps
    needs: build
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/main' || github.ref == 'ref/heads/develop'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PROJECT_NAME}}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}
          package: .
