name: CICD || Build and deploy ASP.Net
run-name: Build and deploy on "${{ github.ref_name }}" by "${{ github.actor }}"

# Only trigger when the code is push or pull request on main or develop.
on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  SOLUTION_FILE_LOCATION: ${{ github.workspace }}/MotoMate.sln
  ARTIFACT_NAME: "dotnet-app"
  PROJECT_NAME: motomate
  SLOT_NAME: "Production"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"
          dotnet-quality: "validated"

      - name: Build with dotnet
        run: dotnet build ${{ env.SOLUTION_FILE_LOCATION }} --configuration Release

      - name: Dotnet publish
        run: dotnet publish ${{ env.SOLUTION_FILE_LOCATION }} -c Release -o ${{ env.DOTNET_ROOT }}/${{ env.ARTIFACT_NAME }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: ${{ env.DOTNET_ROOT }}/${{ env.ARTIFACT_NAME }}

  deploy:
    name: Publish to Azure WebApps
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PROJECT_NAME}}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}
          package: .

      - name: Echo url
        run: |
          echo -e "Published url is: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
