name: Build and deploy ASP.Net
run-name: Build and deploy on "${{ github.ref_name }}" by "${{ github.actor }}"

on:
  push:
    branches: ["main", "develop", "feature/init-github-workflow"]
  pull_request:
    branches: ["main", "develop"]

env:
  SOLUTION_FILE_LOCATION: ${{ github.workspace }}/MotoMate.sln
  RELEASE_PATH: ${{ github.workspace }}/release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"
          dotnet-quality: "validated"

      - name: Build with dotnet
        run: dotnet build $SOLUTION_FILE_LOCATION --configuration Release

      - name: dotnet publish
        run: dotnet publish $SOLUTION_FILE_LOCATION -c Release -o $RELEASE_PATH

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: $RELEASE_PATH

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'GoldenIdea'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4AAA8CAA1F16490CA9BD0C09291FA219 }}
  #         package: .
